name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    - name: Set up Python
      run: uv python install 3.12
    - name: Install dependencies
      run: uv sync --dev
    - name: Run tests
      run: uv run pytest -q
    - name: Validate configuration sync
      run: uv run python scripts/validate-configs.py